on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
        name: Azure Pipelines
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/hancocktech/AgileProject
            azure-pipeline-name: 'webapp2'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}

 